[package]
name = "sirixsh"
version = "0.1.0"
authors = ["Moshe Uminer <47164590+mosheduminer@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
rustyline = "8.2.0"
sirix-rust-client = { git = "https://github.com/sirixdb/sirix-rust-client", rev = "c876e9b6f7ebef9af0e33d6b3dd6f327c2f90bd3", features = ["sync"] }
ureq = "2.1.1"
serde_json = "1.0.64"
minidom = "0.13.0"
quick-xml = { version = "0.22.0", features = ["serialize"]}